# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 10
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: True
      PERF_STAT_FREQUENCY: 40
      ROLLING_BTIME_FREQ: 5
  DATA:
    NUM_DATALOADER_WORKERS: 10
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: sample_index
      INPUT_KEY_NAMES: ["global_views", "local_views", "mask"]
      TARGET_KEY_NAMES: ["mask"]
      TRANSFORMS:
        - name: ImgPilToMultiCrop
          total_num_crops: 12
          size_crops: [224, 96]
          num_crops: [2, 10]
          crop_scales: [[0.25, 1], [0.05, 0.25]]
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          brightness: 0.4
          contrast: 0.4
          saturation: 0.2
          hue: 0.1
        - name: ImgPilMultiCropRandomApply
          transforms: [{"name": "ImgPilGaussianBlur", "p": 1., "radius_min": 0.1, "radius_max": 2.0}]
          prob: [1., 0.1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
        - name: ImgPilMultiCropRandomApply
          transforms: [{"name": "ImgPilRandomSolarize", "p": 1.}]
          prob: [0., 0.2, 0., 0., 0., 0., 0, 0, 0, 0, 0, 0]
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        - name: MaskedImageModeling
          pred_ratio_mean: [0.0, 0.3]
          pred_ratio_var: [0.0, 0.2]
          patch_size: 16
      COLLATE_FUNCTION: ibot_multicrop_masking_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DROP_LAST: True
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  METERS:
    name: ""
  MODEL:
    GRAD_CLIP:
      USE_GRAD_CLIP: True
      NORM_TYPE: 2
      MAX_NORM: 3
    TRUNK:
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        NUM_LAYERS: 12
        NUM_HEADS: 6
        HIDDEN_DIM: 384
        MLP_DIM: 1536
        CLASSIFIER: token
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.1 # stochastic depth dropout probability
        MASKED_IMAGE_MODELING:
          NAME: 'ibot'
          PARAMS: {}
    MULTI_INPUT_HEAD_MAPPING: [
      ["global_views", {"feat_names": ["lastBLK"], "additional_keys": ["mask"]}],
      ["local_views", {"feat_names": ["lastCLS"]}],
    ]
    HEAD:
      PARAMS: [
        ["ibot_head", {
          "in_dim": 384,
          "out_dim": 8192,
          "shared_head": True,
          "normalize_last_layer": False,
        }],
      ]
    TEMP_FROZEN_PARAMS_ITER_MAP: [
      ['module.heads.0.prototypes0.weight_v', 1251],
      ['module.heads.0.prototypes0.weight_g', 1251],
      ['module.heads.0.prototypes1.weight_v', 1251],
      ['module.heads.0.prototypes1.weight_g', 1251],
    ]
    AMP_PARAMS:
      AMP_TYPE: pytorch
      USE_AMP: True
  LOSS:
    name: ibot_loss
    ibot_loss:
      student_temp: 0.1
      center_momentum: 0.9
      center_momentum2: 0.9
      lambda1: 1.0
      lambda2: 1.0
  OPTIMIZER:
    name: adamw
    momentum: 0.9
    nesterov: False
    num_epochs: 300
    param_group_constructor: dino
    regularize_bn: False
    regularize_bias: False
    param_schedulers:
      lr:
        name: composite
        schedulers:
          - name: linear
            start_value: 0.0001
            end_value: 0.002
          - name: cosine
            start_value: 0.002
            end_value: 0.000001
        update_interval: epoch
        interval_scaling: [rescaled, fixed]
        lengths: [0.0333, 0.9667]
      weight_decay:
        name: cosine
        start_value: 0.04
        end_value: 0.4
        update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 2
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 5
    OVERWRITE_EXISTING: true
  SLURM:
    CONSTRAINT: volta32gb
