# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["concatCLS4", ["Identity", []] ],
        ["lastCLS", ["Identity", []] ],
      ]
    TRUNK: # L-16
      NAME: beit
      BEIT:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        NUM_LAYERS: 24
        NUM_HEADS: 16
        HIDDEN_DIM: 1024
        MLP_RATIO: 4.0
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        DROP_PATH_RATE: 0.1 # stochastic depth dropout probability
        QKV_BIAS: True
        QK_SCALE: False # Scale
        USE_ABS_POS_EMB: True
        USE_REL_POS_BIAS: True
        USE_SHARED_REL_POS_BIAS: False
        USE_MEAN_POOLING: False
        INIT_VALUES: 1e-5
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 4096, "dims": [4096, 6]}],
        ["eval_mlp", {"in_channels": 1024, "dims": [1024, 6]}],
      ]
  OPTIMIZER:
      regularize_bn: True
