# @package _global_
config:
  DATA:
    NUM_DATALOADER_WORKERS: 10
    TRAIN:
      BATCHSIZE_PER_REPLICA: 16
  MODEL:
    TRUNK:
      NAME: swin_transformer
      SWIN_TRANSFORMER:
        IMAGE_SIZE: 224
        EMBED_DIM: 192
        DEPTHS: [2, 2, 18, 2]
    HEAD:
      PARAMS: [
        ["dino_head", {
          "in_dim": 1536,
          "num_clusters": [65536],
          "normalize_last_layer": True,
        }],
      ]
    GRAD_CLIP:
      USE_GRAD_CLIP: True
      NORM_TYPE: 2
      MAX_NORM: 3
  DISTRIBUTED:
    NUM_NODES: 8
    NUM_PROC_PER_NODE: 8
