# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
          interpolation: 3
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["lastCLS", ["Identity", []] ],
        ["lastCLS", ["Identity", []] ],
      ]
    TRUNK: # S-16
      NAME: xcit
      XCIT:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        HIDDEN_DIM: 384
        NUM_LAYERS: 12
        NUM_HEADS: 8
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        DROP_PATH_RATE: 0.05
        ETA: 1
        TOKENS_NORM: True
        QKV_BIAS: True
        QK_SCALE: False
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 384, "dims": [384, 1000]}],
        ["mlp", {"dims": [384, 1000]}],
      ]
  OPTIMIZER:
    regularize_bn: True
