# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
          interpolation: 3
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      TRANSFORMS:
        - name: Resize
          size: 256
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["concatPOOL4", ["Identity", []] ],
        ["lastPOOL", ["Identity", []] ],
        ["concatPOOL4", ["Identity", []] ],
        ["lastPOOL", ["Identity", []] ],
      ]
    TRUNK: # B-16
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        NUM_LAYERS: 12
        NUM_HEADS: 12
        HIDDEN_DIM: 768
        MLP_DIM: 3072
        DROPOUT_RATE: 0.0
        ATTENTION_DROPOUT_RATE: 0
        CLASSIFIER: token
        QKV_BIAS: True
        DROP_PATH_RATE: 0.1 # stochastic depth dropout probability
        USE_CLASS_TOKEN: False
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 3072, "dims": [3072, 1000]}],
        ["eval_mlp", {"in_channels": 768, "dims": [768, 1000]}],
        ["mlp", {"dims": [3072, 1000]}],
        ["mlp", {"dims": [768, 1000]}],
      ]
