MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    # NORM: "SyncBN"
    NORM: "BN"
    STRIDE_IN_1X1: False
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    SCORE_THRESH_TEST: 0.50
DATASETS:
  TRAIN: ("GJO_train_2076",)
  TEST: ("GJO_val_2076",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TEST:
  PRECISE_BN:
    ENABLED: True
  EVAL_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: "RGB" # torchvision models take RGB input
VERSION: 2
