# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res5", ["AdaptiveAvgPool2d", [[1, 1]]]],
      ]
    TRUNK:
      NAME: regnet  # This could be overriden by command line to be regnet_fsdp
      REGNET:
        # The following is the same as the model "regnet_y_16gf: from ClassyVision/classy_vision/models/regnet.py
        depth: 18
        w_0: 200
        w_a: 106.23
        w_m: 2.48
        group_width: 112
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [3024, 10]}],
      ]
