# @package _global_
config:
  MODEL:
    TRUNK: # S-8
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 8
        NUM_LAYERS: 12
        NUM_HEADS: 6
        HIDDEN_DIM: 384
        MLP_DIM: 1536
        DROPOUT_RATE: 0.0
        ATTENTION_DROPOUT_RATE: 0
        CLASSIFIER: token
        QKV_BIAS: True
        DROP_PATH_RATE: 0.0
