# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 128
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
          interpolation: 3
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      BATCHSIZE_PER_REPLICA: 256
      TRANSFORMS:
        - name: Resize
          size: 256
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["concatPOOL4", ["Identity", []] ],
        ["lastPOOL", ["Identity", []] ],
        ["concatPOOL4", ["Identity", []] ],
        ["lastPOOL", ["Identity", []] ],
      ]
    TRUNK: # H-14
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 14
        NUM_LAYERS: 32
        NUM_HEADS: 16
        HIDDEN_DIM: 1280
        MLP_DIM: 5120
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.3
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 5120, "dims": [5120, 100]}],
        ["eval_mlp", {"in_channels": 1280, "dims": [1280, 100]}],
        ["mlp", {"dims": [5120, 100]}],
        ["mlp", {"dims": [1280, 100]}],
      ]
