# @package _global_
config:
  MODEL:
    TRUNK: # L-16
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        NUM_LAYERS: 24
        NUM_HEADS: 16
        HIDDEN_DIM: 1024
        MLP_DIM: 4096
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        CLASSIFIER: token
        QKV_BIAS: True
        DROP_PATH_RATE: 0.0
