# @package _global_
config:
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [disk_filelist]
      DATASET_NAMES: [imagenet22k_filelist]
      BATCHSIZE_PER_REPLICA: 10
      MMAP_MODE: False
      COPY_DESTINATION_DIR: /tmp/imagenet22k/
  OPTIMIZER:
    num_epochs: 27
  CHECKPOINT:
    CHECKPOINT_FREQUENCY: 1
