# @package _global_
config:
  TEST_ONLY: True
  DATA:
    TEST:
      DATA_SOURCES: [disk_filelist]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [objectnet_filelist]
      TRANSFORMS:
        - name: OneHotEncode
          num_classes: 1000
        - name: Resize
          size: 224
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  METERS:
    model_output_mask: True
